version: '3.2'
services:
  server:
    build: .
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=asd123.
      - MYSQL_DATABASE=test
    depends_on: [ db ]
    ports:
      - "3001:3001"
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=asd123.
      - MYSQL_DATABASE=test
